# --- !Ups
TRUNCATE TABLE "USERS";

ALTER TABLE "USERS"
ADD COLUMN "COMPANY_ID" INT;

INSERT INTO "USERS" ("NAME", "AGE", "COMPANY_ID") VALUES ('Alice', 30, 1);
INSERT INTO "USERS" ("NAME", "AGE", "COMPANY_ID") VALUES ('Bob', 25, 1);
INSERT INTO "USERS" ("NAME", "AGE", "COMPANY_ID") VALUES ('Charlie', 35, 2);

ALTER TABLE "USERS"
ADD CONSTRAINT FK_COMPANY_ID
FOREIGN KEY ("COMPANY_ID") REFERENCES "COMPANIES"("ID");

# --- !Downs

TRUNCATE TABLE "USERS";

ALTER TABLE "USERS"
DROP CONSTRAINT "FK_COMPANY_ID";

ALTER TABLE "USERS"
DROP COLUMN "COMPANY_ID";

INSERT INTO "USERS" ("NAME", "AGE") VALUES ('Alice', 30);
INSERT INTO "USERS" ("NAME", "AGE") VALUES ('Bob', 25);
INSERT INTO "USERS" ("NAME", "AGE") VALUES ('Charlie', 35);
